# Generated by Django 2.2.3 on 2019-07-10 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManageAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=30)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 7, 11, 1, 50, 21, 950339))),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2019, 7, 11, 1, 50, 21, 950339))),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='assets',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 1, 50, 21, 949341)),
        ),
        migrations.AlterField(
            model_name='assets',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 1, 50, 21, 949341)),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='activities',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminManageAPI.Assets'),
        ),
    ]
