# Generated by Django 2.2.3 on 2019-07-10 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManageAPI', '0005_auto_20190711_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 3, 47, 17, 329103)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 3, 47, 17, 329103)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 3, 47, 17, 328105)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 3, 47, 17, 328105)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 3, 47, 17, 329103)),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='skills',
        ),
        migrations.AddField(
            model_name='worker',
            name='skills',
            field=models.CharField(default='cleaner', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 3, 47, 17, 329103)),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
